/**
 * TravelGuide API
 * Documentació que correspon a l'API de l'aplicació TravelGuide
 *
 * OpenAPI spec version: 1.0.0-oas3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Model basic pels usuaris
 */
export interface User {
    id: number;
    email?: string;
    userName?: string;
    password?: string;
    birthDate?: string;
    profilePhoto?: string;
    points?: number;
    role?: string;
    blocked?: boolean;
}
